### ISSUE TITLE
Timed out tests shouldn't be requeued

### ISSUE THREAD

**Issue by casperisfine** [Shopify/ci-queue#12]
In the following scenario:

  - Worker A pop a test and get stuck until timeout is reached
  - Worker B steal it from worker A and work it off successfully.
  - Worker A finally complete the test with a failure.

Expected behavior:

  Worker A should see that the test was already acknowledged by another worker and simply drop the result.

Current behavior:

  The test is requeued by worker A

Discovered by @lugray

**Comment by lugray** [comment]
It would be awesome if the solution could involve worker A stopping work on the test as soon as worker B reports the test 💚 .  Not infrequently summary is green while a couple of workers stay yellow, waiting for timeout.

**Comment by casperisfine** [comment]
Not a bad idea, but that would require to watch redis from another thread, and then figure out a way to safely interrupt the main thread which is close to impossible unfortunately :/.

**Comment by casperisfine** [comment]
Fixed among other edge cases via https://github.com/Shopify/ci-queue/commit/653de496b71f5518ca9a0eca8a03084b0fa0e9d8
