### ISSUE TITLE
Q: Is ordering of tests in the queue based on previous timing statistics?

### ISSUE THREAD

**Issue by agis** [Shopify/ci-queue#133]
Hello!

We're in the process of evaluating ci-queue for our RSpec suite and I'd like to know: is the timing of a previous example run taken into account when scheduling the example in future builds? E.g. "schedule slower examples first".

Thanks in advance!

**Comment by casperisfine** [comment]
No. It's a fully randomized shuffle. However each worker pick the examples one by one.

In practice it means that as long as you don't have some particularly long example, all the workers should be well balanced.

If your tests runtime are particularly unbalance, then knapsack might be a better option for you, but then it needs frequent rebalancing, hence why we believe it's an inferior solution in practice.

**Comment by agis** [comment]
Thank you!

**Comment by casperisfine** [comment]
Also in case it's not clear. With ci-queue the unit of work is individual `it` blocks, not entire `_spec.rb` files (I'm not quite up to date on RSpec terminology).
