### ISSUE TITLE
Add python support to ci-queue

### ISSUE THREAD

**Issue by solackerman** [Shopify/ci-queue#14]
It would be great if ci-queue supported testing in other languages/frameworks, such as python's pytest. 
The current way we get python tests to run tests off a ci queue is to load the queue with tests using the following command:
```
py.test -q --collect-only
```
and use [pytest_redis](https://github.com/Shopify/pytest-redis) to pull the tests off the queue and run them
```
py.test -vv --junitxml=pytest.xml -p pytest_redis \
           --redis-host=#{redis_host} \
           --redis-port=#{redis_port} \
           --redis-list-key=#{redis_list_key} \
           --redis-backup-list-key=#{redis_backup_list_key}"
```

cc/ @Shopify/byroot @casperisfine

**Comment by casperisfine** [comment]
This is done.
