### ISSUE TITLE
Do you use this in conjunction with Rails 6 parallel tests?

### ISSUE THREAD

**Issue by rmacklin** [Shopify/ci-queue#154]
:wave: &nbsp; This gem looks really interesting! Forgive me for asking what might be a dumb question...

I have an application whose test suite I've parallelized in two levels. First, the test files are split up across a dozen or two containers (using [`circleci tests glob "test/system/**/*_test.rb" | circleci tests split --split-by=timings`](https://circleci.com/docs/2.0/parallelism-faster-jobs/#splitting-by-timing-data)). Second, each container runs its test using a few parallel processes (via the [`parallelize` method from Rails 6](https://guides.rubyonrails.org/testing.html#parallel-testing-with-processes)). The second level helps to further reduce the overall runtime and can parallelize individual tests within the largest test files.

This has worked pretty well, but sometimes one container is just really slow to start up so we end up with the job waiting on that one container when all the rest have already finished. Here's a particularly egregious example:

![Screen Shot 2020-06-24 at 10 53 10 PM](https://user-images.githubusercontent.com/1863540/85663185-a4c0a300-b66d-11ea-8b8e-90fc2f70e5db.png)

This has led me to look into queueing solutions that would minimize the effects of one slow container, and I happened to find this one, which looks promising. My question is: if I were to adopt this, would I still be able to leverage the second level of Rails' multiple-process parallelism within each container, or are there some incompatibilities that prevent that?

**Comment by casperisfine** [comment]
Honestly no idea. I'd be surprised if it worked out of the box, but it might be possible to make it work. Either way we don't use Rails 6 parallel test.

**Comment by agis** [comment]
@rmacklin Even if you made this work, my gut feeling tells me it wouldn't be more efficient that simply spawning N ci-queue workers (where N=logical core count). YMMV though and this can only be determined by measuring with your specific workload.

**Comment by rmacklin** [comment]
@agis Yeah, I have the same feeling that it might be better to just ditch Rails' `parallelize` method if I adopt this. The nice thing about that method, though, is that it handles wiring up the test processes to talk to different databases; it seems like we'd be responsible for setting that up ourselves if we were just spawning multiple ci-queue workers. Have you done that?

**Comment by agis** [comment]
@rmacklin What we've done (I'm not affiliated with Shopify) is having each worker talk to its own, isolated set of data storages (MySQL, Elasticsearch etc.)
