### ISSUE TITLE
Implement retrying a test in the pytest integration

### ISSUE THREAD

**Issue by solackerman** [Shopify/ci-queue#21]
Currently the pytest implementation of ci does not take advantage of the library's ability to retry a test. The suggested pseudocode implementation can be found in the [readme](https://github.com/Shopify/ci-queue/tree/master/python#basic-interface), but concretely, it will likely involve adding functionality to these [two](https://github.com/Shopify/ci-queue/blob/pytest-plugin/python/ciqueue/pytest.py#L69-L89) [methods](https://github.com/Shopify/ci-queue/blob/pytest-plugin/python/ciqueue/pytest.py#L55-L59)

**Comment by casperisfine** [comment]
I believe this is done as well.

**Comment by solackerman** [comment]
it is. Thanks @casperisfine!
