### ISSUE TITLE
Starscream shows successfully retried tests as errors

### ISSUE THREAD

**Issue by cfournie** [Shopify/ci-queue#48]
On [otherwise good builds](https://buildkite.com/shopify/starscream/builds/93358), retried tests show up as failures in Starscream.

![screen shot 2017-12-12 at 12 27 05 pm](https://user-images.githubusercontent.com/49264/33898966-fdcaec4a-df37-11e7-93d8-439166b60b3b.png)

Despite having been retried successfully.

<details>

Node 2:
```
tests/starscream/loaders/test_sqlalchemy_loaders.py::TestRedshiftLoaderIntegration::test_load_from_scratch_incremental[parquet] FAILED WILL_RETRY 
tests/starscream/loaders/test_sqlalchemy_loaders.py::TestRedshiftLoaderIntegration::test_load_from_scratch_incremental[parquet] SKIPPED
```

Node 3:
```
tests/starscream/loaders/test_sqlalchemy_loaders.py::TestRedshiftLoaderIntegration::test_load_from_scratch_incremental[json] PASSED
```
</details>

cc/ @Shopify/dev-acceleration

**Comment by wvanbergen** [comment]
How are JUnitXML files generated in your stack?

**Comment by cfournie** [comment]
[`py.test` creates it](https://github.com/pytest-dev/pytest/blob/5631a8629696ec649b59feae99f7e7e057579c9b/_pytest/junitxml.py#L412-L434) for us after it's finished running our tests ([which we call in our test runner](https://github.com/Shopify/starscream/blob/ecffc5a7cff0386f96f6fd7944234c4db5940b56/.buildkite/runners/test#L32)).

**Comment by wvanbergen** [comment]
In Ruby's MiniTest, we had to override some behaviour so it treats requeued/retried tests as "skipped" to make all the tooling that is unaware of retries work out of the box. My python knowledge and skills are not enough to know whether that is feasible in your case. What do you think?

**Comment by cfournie** [comment]
We mark as skipped and requeue:

https://github.com/Shopify/ci-queue/blob/7a601e0402e0966000a317993d5f483175089217/python/ciqueue/pytest.py#L95-L99

But I guess not well enough because we're still writing out a failure :|

**Comment by solackerman** [comment]
We modify the stats to look like the test never happened, but we don't remove the test itself.
https://github.com/Shopify/ci-queue/blob/master/python/ciqueue/_pytest/outcomes.py#L95-L97

**Comment by jules2689** [comment]
I think we need to override py tests' Junit then. JUnit output will be very important to CIs and to additional user experience. We're currently writing a command that will pull junit artifacts to run failed tests locally, for example. So I think it's in our best interest to invest some time into making this better in python-land.

@sabidib might be interested in this as I was talking to him about JUnit being required for this.
