### ISSUE TITLE
Skipped tests showing up as errors in summary if another test failed

### ISSUE THREAD

**Issue by lukashlavacka** [Shopify/ci-queue#72]
It looks like that skipped tests are showing up as errors in the list if there is another error happening.

### Examples
https://buildkite.com/shopify/shopify-master/builds/75260 
https://buildkite.com/shopify/shopify-master/builds/75268
https://buildkite.com/shopify/shopify-master/builds/75292

**Comment by casperisfine** [comment]
I don't think it's a ci-queue bug, it's more likely to be caused by the way we parse JUnit.xml in our CI. Also this is a public repo so posting private links ain't great.

I opened another internal issue where we'll investigate this bug.
