### ISSUE TITLE
Document usage

### ISSUE THREAD

**Issue by rafaelfranca** [Shopify/ci-queue#8]
Or remove the TODO from the README if it plug-and-play.

**Comment by casperisfine** [comment]
Definitely no plug and play. I'll take a shot at it tomorrow.

**Comment by fw42** [comment]
FYI someone I met at a conference just asked me for help about how to use this gem. Would be awesome if we could update the README.

cc @ankitagupta12

**Comment by casperisfine** [comment]
I've made significant changes in https://github.com/Shopify/ci-queue/pull/41

The gem now provide a pretty much plug and play CLI for minitest projects, and it's usage is now documented (albeit not perfectly).

Feedback welcome.

**Comment by fw42** [comment]
❤️

**Comment by rafaelfranca** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
